name: split-stages-plan
id: split_stages_plan
description: This benchmark lays out stages for each step of an scRNA-seq pipeline
benchmarker: "Mark Robinson <mark.robinson@mls.uzh.ch>"

# Benchmark configuration
version: "0.0.3"
api_version: "0.4.0"

provenance:
  canonical_url: https://raw.githubusercontent.com/omni-scrna/split-stages-plan/refs/heads/main/benchmark_conda.yaml

# The default software environment for this benchmark.
# One of: apptainer, conda, envmodules.
software_backend: "conda"

# Available software environments
software_environments:
  r_conda:
    name: R conda env (some packages self built)
    conda: envs/r.yml
  scanpy:
    name: scanpy multi-module
    conda: envs/scanpy.yml
  scrapper:
    name: scrapper multi-module
    conda: envs/scrapper.yml
  seurat:
    name: seurat multi-module
    conda: envs/seurat.yml
  metrics:
    name: metrics env
    conda: envs/metrics.yaml
  py_conda:
    name: Python conda env
    conda: envs/py.yml
  integrate:
    name: integration env
    conda: envs/integrate.yml
  annotate:
    name: annotate env
    conda: envs/annotate.yml
  integrate-py:
    name: integration env
    conda: envs/integrate-py.yml


stages:
  - id: DATA
    outputs:
      - id: rawdata_h5ad
        path: "{dataset}.h5ad"
      - id: rawdata_clusters_truth
        path: "{dataset}.clusters_truth.tsv"
      - id: rawdata_clusters_truth_num
        path: "{dataset}.clusters_truth_num.txt"
      - id: properties_info
        path: "{dataset}_properties.yaml"
    modules:
      - id: data
        name: "R-based dataset downloads"
        software_environment: r_conda
        repository:
          url: https://github.com/omni-scrna/1-data
          commit: 14c5ddd
        parameters:
          #- dataset_name: "be1-subset"
          #  batch_var: Sample
          #  labels_var: Sample
          #  sample_var: Sample
          - dataset_name: "be1"
            batch_var: Sample
            labels_var: Sample
            sample_var: Sample
          #- dataset_name: "sc-mix"
          #  batch_var: null
          #  labels_var: cell_line
          #  sample_var: null

  - id: FILT
    inputs:
      - rawdata_h5ad
      - properties_info
    outputs:
      - id: filtered_cellids
        path: "{dataset}_cellids.txt.gz"
    modules:
      - id: fi-scrapper
        name: "scrapper-style filtering"
        software_environment: "scrapper"
        repository:
          url: https://github.com/omni-scrna/scrapper
          commit: 18843a7
          entrypoint: filter

  - id: NORM
    inputs:
      - rawdata_h5ad
      - filtered_cellids
    outputs:
      - id: normalized_h5
        path: "{dataset}_normalized.h5"
    modules:
      - id: nr-scrapper
        name: "scrapper-based normalization"
        software_environment: "scrapper"
        repository:
          url: https://github.com/omni-scrna/scrapper
          commit: 18843a7
          entrypoint: normalize
      - id: nr-scanpy
        name: "Python-based scRNA-seq normalization methods"
        software_environment: "py_conda"
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 53eb292
          entrypoint: normalize
        parameters:
          - flavor: ["log1pCP10k"]

  - id: FEAT
    inputs:
      - rawdata_h5ad
      - normalized_h5
      - filtered_cellids
      - properties_info
    outputs:
      - id: normalized_selected_h5
        path: "{dataset}_normalized_selected.h5"
    modules:
      - id: fe-seurat
        name: "seurat-based gene selection"
        software_environment: "seurat"
        repository:
          url: https://github.com/omni-scrna/seurat
          commit: ccb7018
          entrypoint: select
        parameters:
          - selection_type: ["seurat_vst", "seurat_vst_batch"]
            number_selected: 2000
      - id: fe-scrapper
        name: "scrapper-based gene selection"
        software_environment: "scrapper"
        repository:
          url: https://github.com/omni-scrna/scrapper
          commit: 18843a7
          entrypoint: select
        parameters:
          - number_selected: 2000
      - id: fe-scanpy
        name: "scanpy-based gene selection"
        software_environment: "scanpy"
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 53eb292
          entrypoint: feat-select
        parameters:
          - flavor: ["pearson_residuals", "scanpy_seurat"]
            number_selected: 2000

  - id: PCA
    resources:
      cores: 4
    inputs:
      - normalized_selected_h5
    outputs:
      - id: pcas_tsv
        path: "{dataset}_pcas.tsv"
      - id: loadings_tsv
        path: "{dataset}_loadings.tsv"
    modules:
      - id: pc-scanpy
        name: "scanpy PCA"
        software_environment: "scanpy"
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 53eb292
          entrypoint: pca
        parameters:
          - solver: [arpack, randomized]
            n_components: 50
            random_seed: 42
      - id: pc-scrapper
        name: "scrapper PCA"
        software_environment: "scrapper"
        repository:
          url: https://github.com/omni-scrna/scrapper
          commit: 18843a7
          entrypoint: pca
        parameters:
          - solver: [exact, irlba, random]
            n_components: 50
            random_seed: 42

  - id: EMBED-M
    inputs:
      - pcas_tsv
      - rawdata_clusters_truth
    outputs:
      - id: embedding_metrics
        path: "{dataset}_embedding_metrics.json"
    modules:
      - id: em-metrics-py
        name: "Embedding metrics in python"
        software_environment: "metrics"
        repository:
          url: https://github.com/omni-scrna/metrics
          commit: 646f1e4
          entrypoint: embedding-py
      - id: em-metrics-r
        name: "Embedding metrics in R"
        software_environment: "metrics"
        repository:
          url: https://github.com/omni-scrna/metrics
          commit: 646f1e4
          entrypoint: embedding-r

  - id: NNG
    inputs:
      - pcas_tsv
    outputs:
      - id: neighbors_h5
        path: "{dataset}_neighbors.h5"
    modules:
      - id: nn-scanpy
        name: "scanpy KNN graph"
        software_environment: "scanpy"
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 53eb292
          entrypoint: knn
        parameters:
          - n_neighbors: 15
            random_seed: 42
            flavor: "umap"

  - id: GRAPH-M
    inputs:
      - neighbors_h5
      - rawdata_clusters_truth
    outputs:
      - id: graph_metrics
        path: "{dataset}_graph_metrics.json"
    modules:
      - id: nn-metrics-r
        name: "Graph metrics in R"
        software_environment: "metrics"
        repository:
          url: https://github.com/omni-scrna/metrics
          commit: 646f1e4
          entrypoint: graph-r

  - id: GEOM-M
    inputs:
      - pcas_tsv
      - neighbors_h5
    outputs:
      - id: geometry_metrics
        path: "{dataset}_geometry_metrics.json"
    modules:
      - id: geometry-metrics-py
        name: "Euclidean-geodesic geometry metrics"
        software_environment: "metrics"
        repository:
          url: https://github.com/omni-scrna/metrics
          commit: fb2895b43ce150db0bf54dfd840c9007084ec29a
          entrypoint: geometry-py

  - id: CLUST
    inputs:
      - neighbors_h5
    outputs:
      - id: clusters_tsv
        path: "{dataset}_clusters.tsv"
    modules: 
      - id: cl-scanpy
        name: "scanpy Leiden clustering"
        software_environment: "scanpy"
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 7cf3472
          entrypoint: cluster
        parameters:
          - flavor: ["igraph", "leidenalg"]
            resolution: [0.5, 1.0]
            random_seed: 42
      - id: cl-seurat
        name: "Seurat clustering"
        software_environment: "seurat"
        repository:
          url: https://github.com/omni-scrna/seurat
          commit: 537d178
          entrypoint: cluster
        parameters:
          - resolution: [0.5, 1.0]
            random_seed: 42
            flavor: ["leiden", "louvain_original"]
        #repository:
        #  url: https://github.com/omni-scrna/seurat
        #  commit: add-clustering
        #  entrypoint: clustering
        #parameters:
        #  - modularity_algorithm: ["louvain_original"]
        #    resolution: [0.5, 1.0]
        #    random_seed: 42
        #  #- modularity_algorithm: ["louvain_original", "louvain_multilevel_refinement", "slm", "leiden"]

  - id: CLUST-M
    inputs:
      - clusters_tsv
      - rawdata_clusters_truth
    outputs:
      - id: cluster_metrics
        path: "{dataset}_cluster_metrics.json"
    modules:
      - id: cl-metrics-r
        name: "Partition metrics in R"
        software_environment: "metrics"
        repository:
          url: https://github.com/omni-scrna/metrics
          commit: 257c952
          entrypoint: cluster-r

  - id: INTG8
    inputs:
      - pcas_tsv
      - loadings_tsv
      - normalized_selected_h5
      - rawdata_h5ad
      - properties_info
    outputs:
      - id: corrected_tsv
        path: "{dataset}_corrected.tsv"
    modules:
      - id: in-harmony
        name: "Harmony batch correction"
        software_environment: "integrate"
        repository:
          url: https://github.com/omni-scrna/7-integrate
          commit: d42312a
          entrypoint: harmony-r
        parameters:
          - theta: [0.1, 2]
      - id: in-seurat
        name: "Seurat IntegrateLayers batch correction"
        software_environment: "seurat"
        repository:
          url: https://github.com/omni-scrna/seurat
          commit: ccb7018
          entrypoint: integrate
        parameters:
          - method: [rpca]
            k_anchor: [5, 20]
      - id: in-scanorama
        name: "Scanorama batch correction"
        software_environment: "integrate-py"
        repository:
          url: https://github.com/omni-scrna/7-integrate-py
          commit: 73e3340
          entrypoint: scanorama
        parameters:
          - knn: [20]
            sigma: [15]

  - id: ANNO
    inputs:
    - normalized_selected_h5
    outputs:
    - id: annotations_tsv
      path: '{dataset}_annotations.tsv'
    modules:
    - id: an-singler
      name: singler annotation
      software_environment: annotate
      repository:
        url: https://github.com/omni-scrna/9-annotate
        commit: 1cf58ac
      parameters:
        - reference: ["HumanPrimaryCellAtlasData", "BlueprintEncodeData"]

